touch 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=0&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=1&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"    | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=50&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=2&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"   | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=100&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=3&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=150&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=4&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=200&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=5&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=250&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=6&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=300&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=7&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=350&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=8&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=400&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=9&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null"  | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=450&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=10&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=500&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=11&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=550&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=12&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=600&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=13&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=650&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=14&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=700&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=15&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=50&skip=750&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=16&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
wget -O - "http://www.dominiopublico.gov.br/pesquisa/ResultadoPesquisaObraForm.do?first=47&skip=800&ds_titulo=&co_autor=&no_autor=&co_categoria=&pagina=17&select_action=Submit&co_midia=6&co_obra=&co_idioma=&colunaOrdenar=null&ordem=null" | grep DetalheObraForm | egrep "=[0-9]+'" -o | egrep "[0-9]+" -o >> 1ids.txt
