wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20838" -O 20838.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20501" -O 20501.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50593" -O 50593.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50594" -O 50594.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124133" -O 124133.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30731" -O 30731.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51230" -O 51230.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124153" -O 124153.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20498" -O 20498.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21824" -O 21824.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20681" -O 20681.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22061" -O 22061.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124131" -O 124131.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20485" -O 20485.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51419" -O 51419.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20475" -O 20475.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20493" -O 20493.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20677" -O 20677.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156236" -O 156236.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20849" -O 20849.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50388" -O 50388.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51320" -O 51320.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22048" -O 22048.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20280" -O 20280.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20334" -O 20334.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50447" -O 50447.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20507" -O 20507.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20459" -O 20459.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51496" -O 51496.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50427" -O 50427.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50453" -O 50453.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20841" -O 20841.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30720" -O 30720.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51482" -O 51482.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22126" -O 22126.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=123960" -O 123960.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50718" -O 50718.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=155519" -O 155519.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22130" -O 22130.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22143" -O 22143.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21989" -O 21989.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20873" -O 20873.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20724" -O 20724.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50671" -O 50671.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51234" -O 51234.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156703" -O 156703.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21847" -O 21847.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30744" -O 30744.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124127" -O 124127.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20380" -O 20380.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156245" -O 156245.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22116" -O 22116.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22241" -O 22241.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50601" -O 50601.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51395" -O 51395.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50602" -O 50602.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22194" -O 22194.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22275" -O 22275.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22201" -O 22201.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20816" -O 20816.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20500" -O 20500.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30724" -O 30724.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50460" -O 50460.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50459" -O 50459.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20725" -O 20725.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=42044" -O 42044.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51433" -O 51433.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51412" -O 51412.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50774" -O 50774.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50771" -O 50771.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50768" -O 50768.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50777" -O 50777.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99986" -O 99986.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99987" -O 99987.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21871" -O 21871.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20783" -O 20783.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20287" -O 20287.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20275" -O 20275.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20340" -O 20340.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30729" -O 30729.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22273" -O 22273.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22252" -O 22252.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20702" -O 20702.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50455" -O 50455.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51488" -O 51488.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20804" -O 20804.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124128" -O 124128.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51237" -O 51237.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20781" -O 20781.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22038" -O 22038.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20685" -O 20685.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22271" -O 22271.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20347" -O 20347.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51073" -O 51073.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51078" -O 51078.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51079" -O 51079.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51463" -O 51463.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23833" -O 23833.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30718" -O 30718.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51294" -O 51294.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124135" -O 124135.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47202" -O 47202.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22202" -O 22202.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124130" -O 124130.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51229" -O 51229.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51241" -O 51241.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156244" -O 156244.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51224" -O 51224.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20283" -O 20283.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51400" -O 51400.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50410" -O 50410.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21865" -O 21865.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20288" -O 20288.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20393" -O 20393.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20389" -O 20389.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20278" -O 20278.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22226" -O 22226.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20402" -O 20402.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=159923" -O 159923.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51452" -O 51452.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171907" -O 171907.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51231" -O 51231.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20670" -O 20670.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20405" -O 20405.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20259" -O 20259.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21826" -O 21826.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50489" -O 50489.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20472" -O 20472.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124136" -O 124136.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51464" -O 51464.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23834" -O 23834.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20482" -O 20482.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50599" -O 50599.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50600" -O 50600.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20505" -O 20505.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20824" -O 20824.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156884" -O 156884.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50480" -O 50480.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22204" -O 22204.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20716" -O 20716.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20387" -O 20387.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20675" -O 20675.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=42041" -O 42041.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=42043" -O 42043.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=42042" -O 42042.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=42038" -O 42038.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20282" -O 20282.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50439" -O 50439.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20430" -O 20430.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51415" -O 51415.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99984" -O 99984.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51384" -O 51384.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20707" -O 20707.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22065" -O 22065.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20448" -O 20448.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22187" -O 22187.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50440" -O 50440.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21966" -O 21966.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21975" -O 21975.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21979" -O 21979.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51333" -O 51333.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22052" -O 22052.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51277" -O 51277.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156246" -O 156246.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20843" -O 20843.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=123964" -O 123964.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51350" -O 51350.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20726" -O 20726.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20720" -O 20720.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20715" -O 20715.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156704" -O 156704.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48120" -O 48120.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48121" -O 48121.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50662" -O 50662.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50484" -O 50484.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20736" -O 20736.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51000" -O 51000.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51001" -O 51001.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51002" -O 51002.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51003" -O 51003.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51004" -O 51004.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51005" -O 51005.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50996" -O 50996.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50997" -O 50997.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50999" -O 50999.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50991" -O 50991.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50992" -O 50992.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50993" -O 50993.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50358" -O 50358.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=155522" -O 155522.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51236" -O 51236.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156705" -O 156705.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51428" -O 51428.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20722" -O 20722.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47216" -O 47216.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156238" -O 156238.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21877" -O 21877.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50516" -O 50516.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20510" -O 20510.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99988" -O 99988.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99989" -O 99989.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20246" -O 20246.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21863" -O 21863.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48119" -O 48119.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20842" -O 20842.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156706" -O 156706.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169444" -O 169444.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20758" -O 20758.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51407" -O 51407.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20286" -O 20286.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50486" -O 50486.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156707" -O 156707.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50448" -O 50448.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51434" -O 51434.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20464" -O 20464.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22237" -O 22237.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50432" -O 50432.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20476" -O 20476.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20484" -O 20484.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=17623" -O 17623.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20780" -O 20780.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20713" -O 20713.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51423" -O 51423.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100001" -O 100001.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100004" -O 100004.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100003" -O 100003.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100000" -O 100000.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100002" -O 100002.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51396" -O 51396.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51398" -O 51398.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50624" -O 50624.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50629" -O 50629.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50633" -O 50633.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51145" -O 51145.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51146" -O 51146.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51148" -O 51148.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51091" -O 51091.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51093" -O 51093.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51140" -O 51140.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51141" -O 51141.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51142" -O 51142.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51144" -O 51144.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50457" -O 50457.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22027" -O 22027.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124129" -O 124129.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51149" -O 51149.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51156" -O 51156.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51157" -O 51157.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156240" -O 156240.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54430" -O 54430.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22213" -O 22213.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22195" -O 22195.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=123961" -O 123961.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20487" -O 20487.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22196" -O 22196.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51401" -O 51401.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20277" -O 20277.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50437" -O 50437.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20878" -O 20878.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100005" -O 100005.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100009" -O 100009.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100006" -O 100006.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100007" -O 100007.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100008" -O 100008.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50498" -O 50498.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47212" -O 47212.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51171" -O 51171.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51172" -O 51172.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51507" -O 51507.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124152" -O 124152.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124146" -O 124146.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51165" -O 51165.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51167" -O 51167.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51169" -O 51169.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20679" -O 20679.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30726" -O 30726.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51233" -O 51233.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50445" -O 50445.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50449" -O 50449.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50456" -O 50456.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20503" -O 20503.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21850" -O 21850.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20255" -O 20255.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51427" -O 51427.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=193844" -O 193844.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20683" -O 20683.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20704" -O 20704.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50512" -O 50512.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28212" -O 28212.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28217" -O 28217.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3830" -O 3830.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28209" -O 28209.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28224" -O 28224.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28221" -O 28221.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28211" -O 28211.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3833" -O 3833.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28219" -O 28219.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3826" -O 3826.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28216" -O 28216.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28210" -O 28210.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28215" -O 28215.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3820" -O 3820.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3822" -O 3822.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28214" -O 28214.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3827" -O 3827.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3823" -O 3823.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3825" -O 3825.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28220" -O 28220.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=28218" -O 28218.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51335" -O 51335.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50392" -O 50392.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51280" -O 51280.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20703" -O 20703.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20730" -O 20730.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20710" -O 20710.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20489" -O 20489.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22255" -O 22255.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51424" -O 51424.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20680" -O 20680.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20357" -O 20357.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22050" -O 22050.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51328" -O 51328.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22235" -O 22235.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51316" -O 51316.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20893" -O 20893.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51477" -O 51477.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50742" -O 50742.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50743" -O 50743.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50744" -O 50744.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50737" -O 50737.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50738" -O 50738.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50739" -O 50739.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50727" -O 50727.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50731" -O 50731.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50734" -O 50734.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20822" -O 20822.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20823" -O 20823.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50500" -O 50500.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20382" -O 20382.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50504" -O 50504.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50389" -O 50389.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20480" -O 20480.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51408" -O 51408.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50654" -O 50654.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20721" -O 20721.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20771" -O 20771.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51348" -O 51348.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51417" -O 51417.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=39026" -O 39026.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=39027" -O 39027.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=39028" -O 39028.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54495" -O 54495.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51238" -O 51238.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69982" -O 69982.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69983" -O 69983.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69984" -O 69984.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69985" -O 69985.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69986" -O 69986.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69987" -O 69987.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69988" -O 69988.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69989" -O 69989.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69990" -O 69990.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69991" -O 69991.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69992" -O 69992.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69993" -O 69993.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69994" -O 69994.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69995" -O 69995.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69996" -O 69996.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69997" -O 69997.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69998" -O 69998.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=69999" -O 69999.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70000" -O 70000.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70001" -O 70001.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70002" -O 70002.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70004" -O 70004.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70003" -O 70003.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70005" -O 70005.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70006" -O 70006.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70007" -O 70007.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70008" -O 70008.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70009" -O 70009.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70010" -O 70010.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70011" -O 70011.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70012" -O 70012.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=70013" -O 70013.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20773" -O 20773.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50434" -O 50434.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51441" -O 51441.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51421" -O 51421.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20723" -O 20723.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22017" -O 22017.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51460" -O 51460.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171909" -O 171909.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171908" -O 171908.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50502" -O 50502.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20678" -O 20678.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51265" -O 51265.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20802" -O 20802.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=155521" -O 155521.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156708" -O 156708.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20358" -O 20358.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20368" -O 20368.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20457" -O 20457.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20312" -O 20312.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156709" -O 156709.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47189" -O 47189.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100023" -O 100023.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100022" -O 100022.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100020" -O 100020.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100024" -O 100024.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100021" -O 100021.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100027" -O 100027.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100028" -O 100028.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100026" -O 100026.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100025" -O 100025.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100029" -O 100029.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20351" -O 20351.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51322" -O 51322.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20857" -O 20857.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156241" -O 156241.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50481" -O 50481.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20371" -O 20371.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22272" -O 22272.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20768" -O 20768.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156242" -O 156242.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156243" -O 156243.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99992" -O 99992.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47204" -O 47204.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21874" -O 21874.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22216" -O 22216.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=103170" -O 103170.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=103171" -O 103171.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=103169" -O 103169.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23734" -O 23734.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22215" -O 22215.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51420" -O 51420.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50413" -O 50413.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47206" -O 47206.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20401" -O 20401.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22042" -O 22042.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124137" -O 124137.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20776" -O 20776.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51268" -O 51268.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20712" -O 20712.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20717" -O 20717.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20673" -O 20673.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20422" -O 20422.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156710" -O 156710.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156711" -O 156711.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156712" -O 156712.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50458" -O 50458.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51504" -O 51504.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51505" -O 51505.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51506" -O 51506.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99990" -O 99990.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156239" -O 156239.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20766" -O 20766.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156885" -O 156885.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=159924" -O 159924.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20682" -O 20682.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20374" -O 20374.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50597" -O 50597.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50598" -O 50598.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22047" -O 22047.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20779" -O 20779.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21860" -O 21860.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50732" -O 50732.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50761" -O 50761.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50762" -O 50762.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51286" -O 51286.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=155520" -O 155520.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51429" -O 51429.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50763" -O 50763.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50487" -O 50487.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22054" -O 22054.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50386" -O 50386.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51339" -O 51339.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51501" -O 51501.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51502" -O 51502.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51503" -O 51503.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22045" -O 22045.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22046" -O 22046.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20684" -O 20684.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20856" -O 20856.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20349" -O 20349.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51344" -O 51344.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22141" -O 22141.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20708" -O 20708.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20417" -O 20417.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51228" -O 51228.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3829" -O 3829.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22188" -O 22188.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3832" -O 3832.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3831" -O 3831.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3819" -O 3819.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22062" -O 22062.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20483" -O 20483.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50765" -O 50765.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20839" -O 20839.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99993" -O 99993.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22199" -O 22199.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22210" -O 22210.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20509" -O 20509.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22258" -O 22258.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22059" -O 22059.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22225" -O 22225.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22233" -O 22233.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22238" -O 22238.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50702" -O 50702.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20799" -O 20799.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50495" -O 50495.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124132" -O 124132.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20782" -O 20782.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=146434" -O 146434.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20828" -O 20828.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54472" -O 54472.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169446" -O 169446.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169494" -O 169494.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171910" -O 171910.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51283" -O 51283.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48118" -O 48118.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48122" -O 48122.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48123" -O 48123.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51083" -O 51083.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51084" -O 51084.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51085" -O 51085.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20260" -O 20260.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22198" -O 22198.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20315" -O 20315.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50454" -O 50454.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30722" -O 30722.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124134" -O 124134.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21857" -O 21857.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50451" -O 50451.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20869" -O 20869.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20377" -O 20377.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22192" -O 22192.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22189" -O 22189.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22191" -O 22191.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22190" -O 22190.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20883" -O 20883.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20860" -O 20860.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50493" -O 50493.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47199" -O 47199.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50407" -O 50407.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50431" -O 50431.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=48117" -O 48117.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51080" -O 51080.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51081" -O 51081.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51082" -O 51082.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20889" -O 20889.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=149303" -O 149303.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20506" -O 20506.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20672" -O 20672.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20281" -O 20281.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21958" -O 21958.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22207" -O 22207.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22249" -O 22249.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51447" -O 51447.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22245" -O 22245.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54479" -O 54479.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22040" -O 22040.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51357" -O 51357.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51404" -O 51404.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50576" -O 50576.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50577" -O 50577.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50578" -O 50578.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124138" -O 124138.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51336" -O 51336.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50520" -O 50520.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20890" -O 20890.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30740" -O 30740.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50483" -O 50483.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50436" -O 50436.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=123963" -O 123963.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50425" -O 50425.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20276" -O 20276.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47575" -O 47575.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50452" -O 50452.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50675" -O 50675.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51162" -O 51162.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51163" -O 51163.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51164" -O 51164.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20831" -O 20831.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50442" -O 50442.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50438" -O 50438.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20289" -O 20289.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20290" -O 20290.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51235" -O 51235.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51318" -O 51318.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51325" -O 51325.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22014" -O 22014.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47213" -O 47213.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51337" -O 51337.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20398" -O 20398.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20330" -O 20330.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47208" -O 47208.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20376" -O 20376.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20395" -O 20395.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51332" -O 51332.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20263" -O 20263.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22254" -O 22254.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137195" -O 137195.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137196" -O 137196.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137197" -O 137197.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137198" -O 137198.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137199" -O 137199.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137200" -O 137200.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137201" -O 137201.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3821" -O 3821.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99980" -O 99980.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99982" -O 99982.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99981" -O 99981.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99983" -O 99983.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51492" -O 51492.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22277" -O 22277.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20709" -O 20709.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50430" -O 50430.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20460" -O 20460.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=42045" -O 42045.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21854" -O 21854.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156237" -O 156237.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51226" -O 51226.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20763" -O 20763.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20718" -O 20718.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20727" -O 20727.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51240" -O 51240.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53742" -O 53742.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53743" -O 53743.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53744" -O 53744.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53745" -O 53745.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53746" -O 53746.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53747" -O 53747.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53748" -O 53748.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53749" -O 53749.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53750" -O 53750.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53751" -O 53751.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53752" -O 53752.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53753" -O 53753.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53754" -O 53754.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53755" -O 53755.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53756" -O 53756.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53757" -O 53757.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53758" -O 53758.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53759" -O 53759.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=53760" -O 53760.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51425" -O 51425.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20891" -O 20891.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22253" -O 22253.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30712" -O 30712.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20705" -O 20705.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20669" -O 20669.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20414" -O 20414.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50387" -O 50387.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50443" -O 50443.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50391" -O 50391.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22230" -O 22230.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20864" -O 20864.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20701" -O 20701.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22057" -O 22057.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22039" -O 22039.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20308" -O 20308.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3824" -O 3824.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51056" -O 51056.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51059" -O 51059.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51062" -O 51062.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=3828" -O 3828.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20284" -O 20284.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51414" -O 51414.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20853" -O 20853.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20674" -O 20674.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50497" -O 50497.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20835" -O 20835.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22227" -O 22227.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50405" -O 50405.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99991" -O 99991.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124140" -O 124140.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22110" -O 22110.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22212" -O 22212.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50390" -O 50390.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22224" -O 22224.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21948" -O 21948.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51406" -O 51406.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20504" -O 20504.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21830" -O 21830.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99994" -O 99994.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21828" -O 21828.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22056" -O 22056.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54486" -O 54486.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22274" -O 22274.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20666" -O 20666.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20431" -O 20431.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21869" -O 21869.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20462" -O 20462.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51225" -O 51225.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30738" -O 30738.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171912" -O 171912.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20762" -O 20762.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20719" -O 20719.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20714" -O 20714.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20461" -O 20461.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51227" -O 51227.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22049" -O 22049.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=155523" -O 155523.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20458" -O 20458.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50503" -O 50503.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20855" -O 20855.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20892" -O 20892.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20667" -O 20667.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20432" -O 20432.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21827" -O 21827.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20355" -O 20355.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20279" -O 20279.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51271" -O 51271.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124139" -O 124139.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50399" -O 50399.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=57286" -O 57286.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50396" -O 50396.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=47192" -O 47192.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22044" -O 22044.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20412" -O 20412.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21825" -O 21825.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20384" -O 20384.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20379" -O 20379.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20424" -O 20424.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20420" -O 20420.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20668" -O 20668.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51064" -O 51064.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51066" -O 51066.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51069" -O 51069.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51086" -O 51086.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51087" -O 51087.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51089" -O 51089.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50591" -O 50591.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50592" -O 50592.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=157703" -O 157703.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20490" -O 20490.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20850" -O 20850.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171913" -O 171913.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20410" -O 20410.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51239" -O 51239.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20794" -O 20794.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20800" -O 20800.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20859" -O 20859.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=30735" -O 30735.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=4910" -O 4910.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51223" -O 51223.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51430" -O 51430.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20858" -O 20858.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=135322" -O 135322.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137600" -O 137600.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137593" -O 137593.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137597" -O 137597.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137595" -O 137595.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137594" -O 137594.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137598" -O 137598.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137599" -O 137599.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=137596" -O 137596.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51327" -O 51327.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51222" -O 51222.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22142" -O 22142.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50485" -O 50485.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99995" -O 99995.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99996" -O 99996.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99997" -O 99997.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99998" -O 99998.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99999" -O 99999.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100017" -O 100017.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100019" -O 100019.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100018" -O 100018.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100015" -O 100015.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100016" -O 100016.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100013" -O 100013.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100011" -O 100011.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100010" -O 100010.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100012" -O 100012.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50461" -O 50461.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=100014" -O 100014.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51221" -O 51221.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=123962" -O 123962.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54417" -O 54417.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=156886" -O 156886.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51232" -O 51232.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22091" -O 22091.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=54492" -O 54492.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=2220" -O 2220.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=4568" -O 4568.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20854" -O 20854.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20285" -O 20285.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22051" -O 22051.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50450" -O 50450.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50510" -O 50510.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51158" -O 51158.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51160" -O 51160.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51161" -O 51161.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50590" -O 50590.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51440" -O 51440.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20706" -O 20706.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=99985" -O 99985.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22053" -O 22053.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50446" -O 50446.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20352" -O 20352.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20711" -O 20711.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22060" -O 22060.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20508" -O 20508.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50519" -O 50519.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50514" -O 50514.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22228" -O 22228.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169441" -O 169441.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169442" -O 169442.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169443" -O 169443.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50508" -O 50508.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22193" -O 22193.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23550" -O 23550.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23551" -O 23551.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51462" -O 51462.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23838" -O 23838.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=169445" -O 169445.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=124141" -O 124141.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50707" -O 50707.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50710" -O 50710.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50715" -O 50715.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20757" -O 20757.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171914" -O 171914.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50506" -O 50506.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20747" -O 20747.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22055" -O 22055.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=171920" -O 171920.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20265" -O 20265.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50693" -O 50693.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50433" -O 50433.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50595" -O 50595.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50596" -O 50596.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51471" -O 51471.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20801" -O 20801.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20803" -O 20803.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=50415" -O 50415.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51442" -O 51442.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51356" -O 51356.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51410" -O 51410.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=51354" -O 51354.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20745" -O 20745.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=22214" -O 22214.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23730" -O 23730.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=23731" -O 23731.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=21829" -O 21829.html 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraForm.do?select_action=&co_obra=20676" -O 20676.html 
