wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20838" -O 20838.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20501" -O 20501.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50593" -O 50593.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50594" -O 50594.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124133" -O 124133.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=30731" -O 30731.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51230" -O 51230.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124153" -O 124153.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20498" -O 20498.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21824" -O 21824.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20681" -O 20681.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22061" -O 22061.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124131" -O 124131.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20485" -O 20485.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51419" -O 51419.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20475" -O 20475.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20493" -O 20493.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20677" -O 20677.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156236" -O 156236.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20849" -O 20849.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50388" -O 50388.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51320" -O 51320.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22048" -O 22048.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20280" -O 20280.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20334" -O 20334.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50447" -O 50447.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20507" -O 20507.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20459" -O 20459.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51496" -O 51496.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50427" -O 50427.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50453" -O 50453.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20841" -O 20841.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=30720" -O 30720.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51482" -O 51482.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22126" -O 22126.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=123960" -O 123960.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50718" -O 50718.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=155519" -O 155519.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22130" -O 22130.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22143" -O 22143.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21989" -O 21989.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20873" -O 20873.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20724" -O 20724.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50671" -O 50671.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51234" -O 51234.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156703" -O 156703.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21847" -O 21847.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=30744" -O 30744.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124127" -O 124127.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20380" -O 20380.mp4 
