wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156245" -O 156245.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22116" -O 22116.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22241" -O 22241.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50601" -O 50601.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51395" -O 51395.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50602" -O 50602.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22194" -O 22194.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22275" -O 22275.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22201" -O 22201.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20816" -O 20816.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20500" -O 20500.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=30724" -O 30724.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50460" -O 50460.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50459" -O 50459.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20725" -O 20725.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=42044" -O 42044.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51433" -O 51433.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51412" -O 51412.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50774" -O 50774.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50771" -O 50771.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50768" -O 50768.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50777" -O 50777.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=99986" -O 99986.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=99987" -O 99987.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21871" -O 21871.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20783" -O 20783.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20287" -O 20287.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20275" -O 20275.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20340" -O 20340.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=30729" -O 30729.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22273" -O 22273.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22252" -O 22252.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20702" -O 20702.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50455" -O 50455.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51488" -O 51488.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20804" -O 20804.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124128" -O 124128.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51237" -O 51237.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20781" -O 20781.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22038" -O 22038.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20685" -O 20685.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22271" -O 22271.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20347" -O 20347.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51073" -O 51073.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51078" -O 51078.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51079" -O 51079.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51463" -O 51463.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=23833" -O 23833.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=30718" -O 30718.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51294" -O 51294.mp4 
