wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124135" -O 124135.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=47202" -O 47202.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22202" -O 22202.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124130" -O 124130.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51229" -O 51229.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51241" -O 51241.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156244" -O 156244.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51224" -O 51224.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20283" -O 20283.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51400" -O 51400.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50410" -O 50410.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21865" -O 21865.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20288" -O 20288.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20393" -O 20393.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20389" -O 20389.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20278" -O 20278.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22226" -O 22226.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20402" -O 20402.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=159923" -O 159923.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51452" -O 51452.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=171907" -O 171907.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51231" -O 51231.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20670" -O 20670.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20405" -O 20405.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20259" -O 20259.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21826" -O 21826.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50489" -O 50489.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20472" -O 20472.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124136" -O 124136.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51464" -O 51464.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=23834" -O 23834.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20482" -O 20482.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50599" -O 50599.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50600" -O 50600.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20505" -O 20505.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20824" -O 20824.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156884" -O 156884.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50480" -O 50480.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22204" -O 22204.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20716" -O 20716.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20387" -O 20387.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20675" -O 20675.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=42041" -O 42041.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=42043" -O 42043.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=42042" -O 42042.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=42038" -O 42038.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20282" -O 20282.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50439" -O 50439.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20430" -O 20430.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51415" -O 51415.mp4 
