wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=99984" -O 99984.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51384" -O 51384.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20707" -O 20707.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22065" -O 22065.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20448" -O 20448.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22187" -O 22187.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50440" -O 50440.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21966" -O 21966.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21975" -O 21975.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21979" -O 21979.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51333" -O 51333.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22052" -O 22052.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51277" -O 51277.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156246" -O 156246.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20843" -O 20843.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=123964" -O 123964.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51350" -O 51350.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20726" -O 20726.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20720" -O 20720.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20715" -O 20715.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156704" -O 156704.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=48120" -O 48120.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=48121" -O 48121.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50662" -O 50662.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50484" -O 50484.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20736" -O 20736.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51000" -O 51000.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51001" -O 51001.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51002" -O 51002.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51003" -O 51003.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51004" -O 51004.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51005" -O 51005.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50996" -O 50996.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50997" -O 50997.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50999" -O 50999.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50991" -O 50991.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50992" -O 50992.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50993" -O 50993.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50358" -O 50358.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=155522" -O 155522.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51236" -O 51236.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156705" -O 156705.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51428" -O 51428.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20722" -O 20722.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=47216" -O 47216.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156238" -O 156238.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21877" -O 21877.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50516" -O 50516.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20510" -O 20510.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=99988" -O 99988.mp4 
