wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=99989" -O 99989.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20246" -O 20246.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=21863" -O 21863.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=48119" -O 48119.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20842" -O 20842.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156706" -O 156706.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=169444" -O 169444.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20758" -O 20758.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51407" -O 51407.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20286" -O 20286.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50486" -O 50486.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156707" -O 156707.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50448" -O 50448.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51434" -O 51434.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20464" -O 20464.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22237" -O 22237.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50432" -O 50432.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20476" -O 20476.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20484" -O 20484.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=17623" -O 17623.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20780" -O 20780.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=20713" -O 20713.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51423" -O 51423.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=100001" -O 100001.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=100004" -O 100004.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=100003" -O 100003.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=100000" -O 100000.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=100002" -O 100002.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51396" -O 51396.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51398" -O 51398.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50624" -O 50624.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50629" -O 50629.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50633" -O 50633.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51145" -O 51145.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51146" -O 51146.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51148" -O 51148.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51091" -O 51091.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51093" -O 51093.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51140" -O 51140.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51141" -O 51141.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51142" -O 51142.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51144" -O 51144.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=50457" -O 50457.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=22027" -O 22027.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=124129" -O 124129.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51149" -O 51149.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51156" -O 51156.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=51157" -O 51157.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=156240" -O 156240.mp4 
wget "http://www.dominiopublico.gov.br/pesquisa/DetalheObraDownload.do?select_action=&co_midia=6&co_obra=54430" -O 54430.mp4 
